version: '2'

services:
  nginx:
    image: demostf/demos.tf
    container_name: nginx
    ports:
      - "${PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - "certs:/etc/nginx/certs:ro"
      - "./api.tmpl:/etc/nginx/conf.d/api.tmpl"
    environment:
     - HOST=${HOST}
    networks:
      - proxy-tier
    depends_on:
      - api
  api:
    image: demostf/api
    container_name: api
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - proxy-tier
      - db-tier
  upload:
    image: nginx
    container_name: upload

  db:
    image: demostf/db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    networks:
      - db-tier

networks:
  proxy-tier:
  db-tier:

volumes:
  certs:
