version: '2'

services:
  frontend:
    restart: always
    image: demostf/demos.tf
    container_name: nginx
    volumes:
      - "certs:/etc/nginx/certs:ro"
      - "./api.tmpl:/etc/nginx/conf.d/api.tmpl"
      - "./static.tmpl:/etc/nginx/conf.d/static.tmpl"
      - "./sync.tmpl:/etc/nginx/conf.d/sync.tmpl"
      - "${DEMO_ROOT}:/demos"
    environment:
     - HOST=${HOST}
     - UPLOAD_FASTCGI=api:9000
     - UPLOAD_SCRIPT=/app/src/public/upload.php
    networks:
      - proxy-tier
    depends_on:
      - api

  api:
    restart: always
    image: demostf/api
    container_name: api
    environment:
      - BASE_HOST=${HOST}
      - DEMO_ROOT=/demos
      - DEMO_HOST=static.$HOST
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - PARSER_URL=${PARSER_BASE_URL}/url
      - APP_ROOT=https://api.$HOST
      - EDIT_SECRET=${EDIT_SECRET}
      - UPLOAD_KEY=${UPLOAD_KEY}
    volumes:
      - "${DEMO_ROOT}:/demos"
    networks:
      - proxy-tier
      - db-tier
      - parser-tier

  parser:
    restart: always
    image: demostf/demoserver
    container_name: parser
    mem_limit: 256m
    networks:
      - parser-tier
  
  sync:
    restart: always
    image: demostf/sync
    container_name: sync
    mem_limit: 128m
    networks:
      - proxy-tier

  db:
    restart: always
    image: demostf/db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS="--no-locale"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    networks:
      - db-tier

  db-refresh:
    restart: always
    image: demostf/postgres_refresh
    container_name: db-refresh
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=db
      - VIEWS=map_list name_list users_named
    networks:
      - db-tier

  proxy:
    restart: always
    image: demostf/proxy
    container_name: proxy
    environment:
    - HOST=$HOST
    - TARGET=nginx
    - CERTBOT_EMAIL=$EMAIL
    networks:
    - proxy-tier
    ports:
    - "80:80"
    - "443:443"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped

networks:
  proxy-tier:
  db-tier:
  parser-tier:

volumes:
  certs:
