version: '2'

services:
  nginx:
    image: demostf/demos.tf
    container_name: nginx
    ports:
      - "${PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - "certs:/etc/nginx/certs:ro"
      - "./api.tmpl:/etc/nginx/conf.d/api.tmpl"
    environment:
     - HOST=${HOST}
     - UPLOAD_FASTCGI=api:9000
     - UPLOAD_SCRIPT=/app/public/upload.php
    networks:
      - proxy-tier
    depends_on:
      - api
  api:
    image: demostf/api
    container_name: api
    environment:
      - BASE_HOST=${HOST}
      - DEMO_ROOT=/demos
      - DEMO_HOST=static.$HOST
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - PARSER_URL=http://parser/parse
      - APP_ROOT=https://api.$HOST
    volumes:
      - "${DEMO_ROOT}:/demos"
    networks:
      - proxy-tier
      - db-tier
      - parser-tier

  parser:
      image: demostf/demoserver
      container_name: parser
      mem_limit: 256m
      restart: unless-stopped
      networks:
        - parser-tier

  db:
    image: demostf/db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    networks:
      - db-tier

networks:
  proxy-tier:
  db-tier:
  parser-tier:

volumes:
  certs:
